### ISSUE TITLE
on-headers does not work in Node 20.11.1 LTS

### ISSUE THREAD

**Issue by sanyam-aggarwal-shipsy** [jshttp/on-headers#11]
I have installed on-headers and @types/on-headers via npm by
```bash
$ npm i @types/on-headers on-headers --save-exact
```

```json
"@types/on-headers": "1.0.3",
"on-headers": "1.0.2",
```

I have imported the package as
```javascript
import onHeaders from 'on-headers';
```

I have used on-headers in a middleware I am using in NestJS

```javascript
export class APIRequestLogger implements NestMiddleware {
	constructor() {}

	use(req: CustomRequest, res: CustomResponse, next: NextFunction) {
		req.x_startAt = undefined;

		// response data
		res.x_startAt = undefined;

		// record request start
		req.x_startAt = process.hrtime();

		const presentTime = new Date();

		onHeaders(res, (): void => {
			res.x_startAt = process.hrtime();
		});

		next();
	}
}

```

When this middleware is invoked on calling APIs, I receive an error
`"(0 , on_headers_1.default) is not a function",`

What am I missing here?

**Comment by jonchurch** [comment]
Thanks for reaching out! Just a heads up, we usually use GitHub issues for bug reports and feature requests. While we'd love to help everyone, we can't offer in-depth support for individual apps here.

The tests succeed for Node 20.11.1, just ran them locally. This is likely an issue with Nest or your application. If you can provide a minimum repro we can reopen and start looking
